"""Fix model relationships

Revision ID: 564a6ff92d7f
Revises: cdeb9d0dbf69
Create Date: 2024-10-17 20:32:49.231200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '564a6ff92d7f'
down_revision: Union[str, None] = 'cdeb9d0dbf69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
