"""added more endpoints

Revision ID: cdeb9d0dbf69
Revises: e0ce479b8110
Create Date: 2024-10-17 20:21:55.690325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdeb9d0dbf69'
down_revision: Union[str, None] = 'e0ce479b8110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
